version: '3'

services:
  web:
    build: .
    volumes:
      - .:/usr/share/nginx:cached
      - ./config/php_dev.conf:/usr/local/etc/php-fpm.d/zz-log.conf:ro

  nginx:
    image: nginx:1.13
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/usr/share/nginx/public:ro
    depends_on:
      - web