version: '3'

services:
  web:
    build: .
    volumes:
      - .:/usr/share/nginx:cached
      - ./config/php.conf:/usr/local/etc/php-fpm.d/zz-log.conf:ro

  nginx:
    image: nginx:1.13
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/usr/share/nginx/public:ro
    depends_on:
      - web

  mysql:
    image: mysql:5.7.24
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./config/mysql.conf:/etc/mysql/conf.d/mysql.conf:ro
    expose:
      - 3306